### PR TITLE
fix(iOS): added iOS12 Lottie.xcframwork

### PR DESCRIPTION
**Pull request by mbender74**
changed manifest to min SDK 10.0.1

Fixes  https://github.com/m1ga/ti.animation/issues/59

### CODE REVIEW

**Comment by mbender74** [comment]
@m1ga because the binary is compiled against 10.0.1.GA ... also since v4.0.0 that was also already so.... 
Should we lower that? 9.2.0 is sooo old.... and MacCatalyst support would not work I assume, but I´m not sure...

**Comment by m1ga** [comment]
I don't know it for iOS but the compile version shouldn't make a difference. So if you compile the module with 10.1.1 and minSDK is 9.x it should still work in 9.x. The only issue that was mentioned in the ticket was that it isn't working with iOS 12 since the included Lottie version was build with a wrong version, right?
But I guess @hansemannn should check that since he has way more iOS knowledge :smile: 

BTW: I've cleaned up the title + description. This way the tickets is linked automatically.

**Comment by m1ga** [comment]
oh and which version of the Lottie Framework do you use? Is it still the old version listed here: https://github.com/m1ga/ti.animation#library-versions

**Comment by mbender74** [comment]
@m1ga I changed the version here: https://github.com/m1ga/ti.animation/pull/60/commits/23e5af330c8e55d570c1e321940a9949df46a062

**Comment by mbender74** [comment]
Next I will try to use the newest Lottie iOS....

**Comment by m1ga** [comment]
> @m1ga ok, but I have concerns from 9.x.x to 10.x.x because on iOS the Ti.UI.window and other things (promise stuff) has changed and that was as example a big issue with NappDrawer... so I would (my modules all) recommend to set 10.0.1 as minimum for future updates

ah I see, thanks for the info!
 If you ask me: 10.0.0+ :smile:  But there are so many people still using 9.x :disappointed: Hopefully that will change with 11 and future updates.

**Comment by mbender74** [comment]
the from me tested 4.0.1 binary is in my repo

**Comment by hansemannn** [comment]
Thanks a lot, @mbender74! :) And yep, I agree with @m1ga on the minversion, we should keep it whenever possible. If not, we need at least a major version update (v5.0.0). Everything else looks good!

**Comment by mbender74** [comment]
@hansemannn @m1ga ok, I changed manifest back to 9.2.0
https://github.com/m1ga/ti.animation/pull/60/commits/4046c74006390f601d6880196d1254f1060fb07e

**Pull request merged**
