### PR TITLE
feat(android): use gradle, update to Lottie 3.0.3

### PR DESCRIPTION
**Pull request by hansemannn**
- [x] Updates the module to use Gradle for it's dependencies
- [x] Update Lottie Android to 3.0.3 (similar to #52 but with Gradle)
- [x] Bump min-sdk version to 9.0.0
- [x] Refactor module source based on Android Studio warnings (yeah, it can actually be opened in Android Studio now)

The module binaries also look different now when extracted. Here is an example: 
[ti.animation-android-4.0.0.zip](https://github.com/m1ga/ti.animation/files/3991476/ti.animation-android-4.0.0.zip). Now takes 119 KB instead of 394 KB for packaging. Even more notable for larger packages.

cc @jquick-axway :)

### CODE REVIEW

**Comment by m1ga** [comment]
nice! I'll take a look at this and SDK9 soon. Looking forward to all the changes

**Comment by hansemannn** [comment]
Most exciting release I've been waiting for so far. Opening a Titanium project in Android Studio is so damn lit.

**Comment by jquick-axway** [comment]
> Opening a Titanium project in Android Studio is so damn lit.

Nice! :)

**For your info:**
We will be adding `x86_64` support to Titanium 9.0.0 soon. Keep an eye out for this PR from Gary. This will involve updating the `manifest` file's `architectures` and `apiversion` entries when building with 9.0.0.

We're still deciding how backward compatibility with older modules will work. The solution may be that if you want x86_64 app build support, then all modules will need to be built with 9.0.0. If at least 1 module is older than 9.0.0, then the app can't be built for x86_64. That is, it's all or nothing.

**Comment by m1ga** [comment]
I see `LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove()` for my test animations. They work fine with the current stable module.
e.g. https://lottiefiles.com/16522-liquid-loading works in 8.3.1 module version but not this one. Changing `mergePath` doesn't make any difference.

**Comment by jquick-axway** [comment]
@m1ga, perhaps you're running into the issue below?
https://github.com/airbnb/lottie-android/issues/1091

@hansemannn, you should delete the "lib" directory. The AAR under it is no longer needed since you are referencing the library via "build.gradle". (I'm kind of surprised you didn't run into a build failure due to a class name collision.)

**Comment by m1ga** [comment]
I'll merge this and update to 3.4.0 from here!

**Pull request merged**
