### PR TITLE
Refactoring of Lottie iOS version

### PR DESCRIPTION
**Pull request by AndreaVitale**
This PR contains:
- [x] Refactoring of Lottie Proxy View and the related View
- [x] Fix the issue #8 
- [x] Updated Lottie to version 2.0.3
- [ ] Autostart fix

To finish this PR I need help on `autostart` that won't work ([L51](https://github.com/AndreaVitale/ti.animation/blob/master/iphone/Classes/Lottie/TiAnimationLottieView.m#L51)).

### CODE REVIEW

**Comment by hansemannn** [comment]
Thanks for the PR! @bduyng opened #21 yesterday, so we need to find a way to properly use the best of both. As your Lottie-version is outdated already again, you might want to check out the other PR and ensure your changes match that one, so we can merge it away and continue fixing the autostart.

**Comment by bduyng** [comment]
@hansemannn thanks! I will check the Lottie version now

**Comment by AndreaVitale** [comment]
Sincerely, before to open this PR, I also tested the latest version of Lottie (2.1.3) but the animation frame rate is really low then 2.0.3 version.
[Here](https://www.dropbox.com/s/1avovbxdlb2hdgb/lottie-2.0.3.mov?dl=0) is a sample with Lottie 2.0.3 and [here](https://www.dropbox.com/s/ixhv9uohrgabzac/lottie-2.1.3.mov?dl=0) is another sample with 2.1.3 version.

@bduyng have you seen the same behavior with your code?

**Comment by hansemannn** [comment]
@AndreaVitale So might this be a Lottie 2.1.x known issue? And please also decide which of the both PR's we should take.

**Comment by AndreaVitale** [comment]
I looked into the already opened issues on Lottie project but I can't find one similar. About deciding with PR you could take, we can wait for @bduyng that can confirm if the frame rate problem is also present for him. If yes, due to the changes amount in my code, you can merge this one for first and after we can port all @bduyng changes into this one.

**Comment by bduyng** [comment]
@AndreaVitale sorry for late response and thanks for a nice catch! I can not find the performance issue on 2.1.3 with my eyes but Instruments shows the problem :). on 2.1.3 we just reach about 45-50 fps

**Comment by hansemannn** [comment]
@AndreaVitale @bduyng So what do you agree one? I'd rather merge this one as it also refactors the view/proxy relation, but the other one seems to have a more updated lottie version. So once it's merged, I will do some additional changes to ensure the outstanding issues are fixed.

**Pull request merged**
