### PR TITLE
Update Lottie iOS to 2.5.0, expose more API's

### PR DESCRIPTION
**Pull request by hansemannn**
- Updates Lottie iOS to 2.5.0
- Deprecates `addViewToLayer` in favor of `addViewToKeypathLayer`
- Adds a few more API's:
  - Method: `convertRectToKeypathLayer`
  - Method: `convertPointToKeypathLayer`
  - Method: `convertRectFromKeypathLayer`
  - Method: `convertPointFromKeypathLayer`
  - Method: `setValueDelegateForKeyPath`
  - Property: `cache` [get/set] 
  - Constants (used in `setValueDelegateForKeyPath.type`):
    - `CALLBACK_COLOR_VALUE`
    - `CALLBACK_NUMBER_VALUE`
    - `CALLBACK_POINT_VALUE`
    - `CALLBACK_SIZE_VALUE`
    - `CALLBACK_PATH_VALUE`

Beta: [ti.animation-iphone-1.3.0.zip](https://github.com/m1ga/ti.animation/files/1734655/ti.animation-iphone-1.3.0.zip)

### CODE REVIEW

**Comment by hansemannn** [comment]
Can someone test this in their local environments?

**Comment by m1ga** [comment]
I can check it but I don't have a access to a Mac or iPhone in the next week, so it takes a bit 😄

**Comment by m1ga** [comment]
tested the linked beta file. Simulator is running the example without a problem.

Didn't test the new APIs; you've got an example on how to use them?

**Comment by m1ga** [comment]
let's merge this since the basic stuff still works and the new stuff might be useful for some people!

**Pull request merged**
