### PR TITLE
[IOS] update lottie-ios to 2.1.0

### PR DESCRIPTION
**Pull request by bduyng**
hi @m1ga I updated lottie-ios to 2.1.0 in this commit and will add more new features soon. Please review and let me know if this able to merge. thanks!

### CODE REVIEW

**Comment by m1ga** [comment]
thanks! @hansemannn could you have a look at it too!

**Comment by hansemannn** [comment]
Yep, saw it. @bduyng Is this ready for review? I wanted to come back to the module this week, and I think another community member (Michael, who was it?) also has an outstanding PR. We should merge one first and then take care of everything outstanding, before drafting the new release.

**Comment by bduyng** [comment]
@hansemannn I think it is ready. I just updated the library and checked with the example project. Furthermore, if you check [here](https://github.com/airbnb/lottie-ios/releases) you will see 2.1.0 fixed a lot of bugs. I also added new apis(tintColor, playFromToProgress, playFromToFrame...) on my fork and ready to merge after this :).

**Comment by bduyng** [comment]
updated Lottie-ios to 2.1.3

**Comment by hansemannn** [comment]
Closing in favor of #22, but still a **huge** thank you! Keep it up for the next updates :-).

**Pull request closed without merging**
